### ISSUE TITLE
Environment Setup error

### ISSUE THREAD

**Issue by RuoMengAwA** [w1oves/DTP#3]
When I run 
```shell
pip install -v -e .
or
python setup.py develop
```
setup.py will push an error :
```
 File "/data/workspace/ray/xiaomai/DTP/setup.py", line 12, in readme
      with open('MMSEG_README.md', encoding='utf-8') as f:
  FileNotFoundError: [Errno 2] No such file or directory: 'MMSEG_README.md'
```
I change the code `MMSEG_README.md` to `README.md`
New error had pushed ,
Checking requirements.txt shows that the requirements folder is missing from the repository

**Comment by w1oves** [comment]
Thank you for your interest in my work! I apologize for omitting the requirements folder when uploading to Github. Fortunately, you pointed out this oversight, and I have now uploaded this folder to the repository. If this work is helpful to you, please give it a star!
