### ISSUE TITLE
A KeyError has occurred

### ISSUE THREAD

**Issue by RuoMengAwA** [w1oves/DTP#4]
> This problem may be my personal problem, but I can't find a solution for the moment because now I haven't other machine. 
* envirment prepare:
```shell
mim list output:
mmcls      0.25.0
mmcv-full  1.7.2
***
pip list output(key package):
torch                  1.13.1+cu116
torchaudio             0.13.1+cu116
torchvision            0.14.1+cu116
mmsegmentation         0.30.0
```
***
* problem description：Firstly，I ran the code
```python
python custom-tools/swin2mmseg.py ./premodel/simmim_pretrain__swin_base__img192_window6__800ep.pth ./checkpoints/simmim_pretrain__swin_base__img192_window6__800ep.pth
```
error output:
```shell
.../python3.10/site-packages/mmcv/utils/registry.py", line 61, in build_from_cfg
    raise KeyError(
KeyError: 'CustomTensorboardLoggerHook is not in the hook registry'
```
***
* detailed description:
I executed the readme.md step in your code without any errors (or solved it myself), and I was able to run the test.py part of your code as normal.
I checked all the possibilities I could think of for this problem, including lowering the mvcc-full version to 1.7.0/1.7.1, But it's obviously useless. The only possibility I can think of is that there are some environment version conflicts. Because the main cuda version on my machine was 12.3 and could not be easily changed, I used the pip installation whl package scenario to install the torch environment that met the project requirements.
So I posed this question to ask if you have encountered this problem while running an existing version of this project, or if you can give me some advice, thank you very much
***
Finally，I think the checkpoints/ & cityscapes/ section of your existing readme.md file structure can be modified. As well as explaining the data generation process for cityscapes (which I inferred from your mention of datasets in your preprint on arxiv), later I hope I can propose a PR for readme.md to your project

**Comment by w1oves** [comment]
Thank you very much for the effort you've made to replicate my work! 
* I am very sorry for the confusion I caused. In fact, CustomTensorboard is a Hook written for debugging purposes, and it's not necessary to release it in this repo. I suspect your error occurred because of this, so I have uploaded a new checkpoint. Additionally, you can resolve this issue by replacing all instances of CustomTensorboard with Tensorboard.
* I am very happy to accept your PR on the readme, and I greatly appreciate it!

**Comment by RuoMengAwA** [comment]
Thank you very much for your help, but it seems that the new checkpoint link permissions you provided are not publicly accessible

**Comment by w1oves** [comment]
It's OK now



---- Replied Message ----
| From | ***@***.***> |
| Date | 02/01/2024 12:27 |
| To | ***@***.***> |
| Cc | WEI, ***@***.***>***@***.***> |
| Subject | Re: [w1oves/DTP] A KeyError has occurred (Issue #4) |

Thank you very much for your help, but it seems that the new checkpoint link permissions you provided are not publicly accessible

**Comment by RuoMengAwA** [comment]
thank for your help.
Now,everything is ok.
After I lowered the samples_per_gpu parameter to reduce the batch_size, I was able to start normal training.

> It's OK now
> […](#)
> ---- Replied Message ---- | From | ***@***.***> | | Date | 02/01/2024 12:27 | | To | ***@***.***> | | Cc | WEI, ***@***.***>***@***.***> | | Subject | Re: [w1oves/DTP] A KeyError has occurred (Issue #4) | Thank you very much for your help, but it seems that the new checkpoint link permissions you provided are not publicly accessible — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you commented.Message ID: ***@***.***>

**Comment by RuoMengAwA** [comment]
I forgot to mention that after changing cfg.py, you need to add a separate line 'pip install tensorboard' in the environment preparation phase.
I will add it in PR later.
thanks again.

**Comment by w1oves** [comment]
Thanks for your effort!
